include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_field: ignore
  exclude:
    - "lib/generated/**"
    - "lib/**/*.config.dart"
    - "lib/**/*.g.dart"

linter:
  rules:
    prefer_single_quotes: true  # Ép dùng nháy đơn ' '
    avoid_print: true           # Cấm dùng lệnh print vô tội vạ
    always_declare_return_types: true # Luôn khai báo kiểu trả về cho hàm
    prefer_const_constructors: true   # Khuyên dùng const để tối ưu hiệu năng UI
    prefer_const_declarations: true   # Khuyên dùng const cho hằng số